#This is a movit contoller connecting follow_joint_trajectory controller with JointTrajectoryController

controller_list:
  - name: robot_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
    - J1
    - J2
    - J3
    - J4
    - J5
    - J6
  - name: hand_ee_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
    - J7
    - J8
